package org.kteam.entity;

import org.kteam.protocol.RSA;
import org.springframework.beans.factory.annotation.Autowired;

    public class Account {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the dbserivce column account.ID
     *
     * @mbggenerated Sun Aug 13 23:51:56 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the dbserivce column account.account_name
     *
     * @mbggenerated Sun Aug 13 23:51:56 CST 2017
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the dbserivce column account.account_psw
     *
     * @mbggenerated Sun Aug 13 23:51:56 CST 2017
     */
    private String accountPsw;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the dbserivce column account.ID
     *
     * @return the value of account.ID
     *
     * @mbggenerated Sun Aug 13 23:51:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the dbserivce column account.ID
     *
     * @param id the value for account.ID
     *
     * @mbggenerated Sun Aug 13 23:51:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the dbserivce column account.account_name
     *
     * @return the value of account.account_name
     *
     * @mbggenerated Sun Aug 13 23:51:56 CST 2017
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the dbserivce column account.account_name
     *
     * @param accountName the value for account.account_name
     *
     * @mbggenerated Sun Aug 13 23:51:56 CST 2017
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the dbserivce column account.account_psw
     *
     * @return the value of account.account_psw
     *
     * @mbggenerated Sun Aug 13 23:51:56 CST 2017
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the dbserivce column account.account_psw
     *
     * @param accountPsw the value for account.account_psw
     *
     * @mbggenerated Sun Aug 13 23:51:56 CST 2017
     */
    public void setAccountPsw(String accountPsw) {
        this.accountPsw = accountPsw == null ? null : accountPsw.trim();
    }

    public String getAccountPsw() {
        return accountPsw;
    }

}